version: '3'
services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx.conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run gunicorn config.wsqi.application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"